In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
teamsdata = pd.read_csv('nbadata.csv', sep = ',')

In [5]:
teamsdata.head()

,Week,Boston Celtics,Philadelphia 76ers,Toronto Raptors,Brooklyn Nets,New York Knicks,Milwaukee Bucks,Cleveland Cavaliers,Chicago Bulls,Indiana Pacers,Detroit Pistons,Atlanta Hawks,Washington Wizards,Miami Heat,Charlotte Hornets,Orlando Magic,Denver Nuggets,Minnesota Timberwolves,Utah Jazz,Portland Trail Blazers,Oklahoma City Thunder,Phoenix Suns,Los Angeles Clippers,Sacramento Kings,Golden State Warriors,Los Angeles Lakers,New Orleans Pelicans,Memphis Grizzlies,Dallas Mavericks,San Antonio Spurs,Houston Rockets
0,12/5/2021,8,5,1,5,5,17,12,29,6,7,6,5,9,7,3,15,12,17,21,13,5,3,2,17,20,3,7,8,6,9
1,12/12/2021,6,7,1,5,8,14,14,16,8,8,6,5,10,5,5,16,20,15,22,8,6,2,2,22,23,3,5,8,4,8
2,12/19/2021,9,5,1,3,8,21,14,27,5,8,8,4,10,5,3,14,14,18,14,11,8,2,2,17,25,3,6,8,6,6
3,12/26/2021,6,5,1,8,5,13,17,32,7,6,6,5,10,5,4,23,15,26,17,11,7,3,2,16,26,3,9,9,5,8
4,1/2/2022,6,5,2,8,6,17,14,34,9,8,8,7,10,6,3,17,16,33,15,8,5,3,2,16,22,4,7,9,3,7

Above is the data I accessed using the Google Trends website. What I had to do to access the data is put each NBA team into google trends search. You are only able to search for 5 'terms' at a time, meaning that I had to search for 5 teams at a time, which I ended up doing by division since the NBA is split up into 6 divisions of 5 teams each. It gave me a .csv file for each search (6 total), which I then wrangled and put it all into one .csv file to have all the data in one file. I also removed some small unnecessary detials from the files.

So above every team is listed and the numbers are the teams popularity on google by week. What i will probably do next is change the dates to grouping by month instead of by week just to have it be easier to read and have less data to have to interpret. 

My end goal will be to look at the total popularity over the year for each team, determine which teams have been the most popular over the last year, as well as look at what times of the year nba teams are trending also what times of the year have the least amount of searches.

In [6]:
teamsdata2 = teamsdata.replace('<1', 1)

There were some teams that had >1 values for their searches for some given weeks, so for the sake of this data, and being able to know what that exact value is, I have replaced all of the '>1" values to just be the value 1

In [20]:
weekmonthdata = pd.read_csv('nbateamsv2.csv', sep = ',')

In [21]:
weekmonthdata.head(11)

,Unnamed: 0,Week,Boston Celtics,Philadelphia 76ers,Toronto Raptors,Brooklyn Nets,New York Knicks,Milwaukee Bucks,Cleveland Cavaliers,Chicago Bulls,Indiana Pacers,Detroit Pistons,Atlanta Hawks,Washington Wizards,Miami Heat,Charlotte Hornets,Orlando Magic,Denver Nuggets,Minnesota Timberwolves,Utah Jazz,Portland Trail Blazers,Oklahoma City Thunder,Phoenix Suns,Los Angeles Clippers,Sacramento Kings,Golden State Warriors,Los Angeles Lakers,New Orleans Pelicans,Memphis Grizzlies,Dallas Mavericks,San Antonio Spurs,Houston Rockets
0,0,1/2/2022,6.0,5.0,2.0,8.0,6.0,17.0,14.0,34.0,9.0,8.0,8.0,7.0,10.0,6.0,3.0,17.0,16.0,33.0,15.0,8.0,5.0,3.0,2.0,16.0,22.0,4.0,7.0,9.0,3.0,7.0
1,1,1/9/2022,6.0,5.0,2.0,6.0,7.0,18.0,18.0,40.0,7.0,9.0,7.0,5.0,11.0,8.0,2.0,17.0,14.0,15.0,16.0,9.0,4.0,2.0,2.0,28.0,18.0,3.0,14.0,9.0,4.0,5.0
2,2,1/16/2022,6.0,5.0,1.0,5.0,7.0,15.0,14.0,29.0,8.0,9.0,7.0,6.0,10.0,6.0,4.0,21.0,18.0,20.0,14.0,8.0,5.0,2.0,2.0,16.0,21.0,3.0,6.0,9.0,4.0,6.0
3,3,1/23/2022,6.0,7.0,1.0,5.0,7.0,16.0,15.0,26.0,6.0,7.0,7.0,5.0,12.0,9.0,3.0,16.0,21.0,21.0,15.0,9.0,6.0,2.0,2.0,14.0,23.0,4.0,5.0,8.0,4.0,4.0
4,4,1/30/2022,7.0,8.0,2.0,6.0,5.0,12.0,15.0,25.0,6.0,8.0,9.0,5.0,11.0,7.0,4.0,19.0,16.0,18.0,20.0,8.0,6.0,3.0,2.0,16.0,17.0,3.0,8.0,9.0,5.0,6.0
5,Janurary,NaN,31.0,30.0,8.0,30.0,32.0,78.0,76.0,154.0,36.0,41.0,38.0,28.0,54.0,36.0,16.0,90.0,85.0,107.0,80.0,42.0,26.0,12.0,10.0,90.0,101.0,17.0,40.0,44.0,20.0,28.0
6,5,2/6/2022,11.0,14.0,2.0,9.0,11.0,28.0,24.0,33.0,12.0,9.0,8.0,7.0,11.0,9.0,4.0,22.0,21.0,26.0,28.0,15.0,8.0,3.0,3.0,13.0,28.0,7.0,6.0,12.0,4.0,6.0
7,6,2/13/2022,9.0,10.0,1.0,8.0,6.0,18.0,12.0,25.0,6.0,6.0,6.0,6.0,11.0,6.0,3.0,15.0,14.0,16.0,16.0,9.0,6.0,4.0,2.0,13.0,16.0,4.0,5.0,8.0,4.0,6.0
8,7,2/20/2022,6.0,9.0,1.0,4.0,4.0,9.0,10.0,19.0,4.0,7.0,5.0,3.0,8.0,4.0,2.0,11.0,15.0,10.0,15.0,8.0,4.0,2.0,1.0,7.0,11.0,3.0,4.0,5.0,3.0,3.0
9,8,2/27/2022,8.0,16.0,2.0,7.0,6.0,22.0,15.0,29.0,7.0,8.0,7.0,5.0,15.0,7.0,3.0,19.0,16.0,18.0,14.0,9.0,7.0,3.0,2.0,12.0,18.0,6.0,9.0,14.0,4.0,6.0
10,Feburary,NaN,34.0,49.0,6.0,28.0,27.0,77.0,61.0,106.0,29.0,30.0,26.0,21.0,45.0,26.0,12.0,67.0,66.0,70.0,73.0,41.0,25.0,12.0,8.0,45.0,73.0,20.0,24.0,39.0,15.0,21.0

in the file im pulling in below I did some more wrangling to get the teams popularity just for every month, above the month is included with every weeks data, below will just me data by month

In [17]:
monthlydata = pd.read_csv('nbateamsmonthly.csv', sep = ',')

In [19]:
monthlydata.head(12)

,Unnamed: 0,Boston Celtics,Philadelphia 76ers,Toronto Raptors,Brooklyn Nets,New York Knicks,Milwaukee Bucks,Cleveland Cavaliers,Chicago Bulls,Indiana Pacers,Detroit Pistons,Atlanta Hawks,Washington Wizards,Miami Heat,Charlotte Hornets,Orlando Magic,Denver Nuggets,Minnesota Timberwolves,Utah Jazz,Portland Trail Blazers,Oklahoma City Thunder,Phoenix Suns,Los Angeles Clippers,Sacramento Kings,Golden State Warriors,Los Angeles Lakers,New Orleans Pelicans,Memphis Grizzlies,Dallas Mavericks,San Antonio Spurs,Houston Rockets
0,Janurary,31.0,30.0,8.0,30.0,32.0,78.0,76.0,154.0,36.0,41.0,38.0,28.0,54.0,36.0,16.0,90.0,85.0,107.0,80.0,42.0,26.0,12.0,10.0,90.0,101.0,17.0,40.0,44.0,20.0,28.0
1,Feburary,34.0,49.0,6.0,28.0,27.0,77.0,61.0,106.0,29.0,30.0,26.0,21.0,45.0,26.0,12.0,67.0,66.0,70.0,73.0,41.0,25.0,12.0,8.0,45.0,73.0,20.0,24.0,39.0,15.0,21.0
2,March,39.0,44.0,10.0,32.0,21.0,78.0,56.0,87.0,21.0,33.0,28.0,24.0,53.0,26.0,16.0,93.0,83.0,76.0,59.0,40.0,28.0,11.0,6.0,51.0,90.0,23.0,31.0,41.0,19.0,25.0
3,April,69.0,53.0,17.0,55.0,12.0,132.0,56.0,125.0,13.0,22.0,66.0,10.0,74.0,21.0,7.0,159.0,248.0,136.0,37.0,27.0,49.0,15.0,5.0,73.0,50.0,68.0,77.0,74.0,16.0,13.0
4,May,288.0,49.0,5.0,6.0,9.0,225.0,18.0,30.0,10.0,17.0,10.0,5.0,286.0,10.0,6.0,22.0,22.0,25.0,29.0,19.0,71.0,5.0,6.0,239.0,32.0,6.0,112.0,272.0,5.0,11.0
5,June,201.0,11.0,4.0,7.0,17.0,21.0,19.0,34.0,11.0,26.0,14.0,7.0,25.0,11.0,7.0,24.0,30.0,44.0,37.0,27.0,7.0,5.0,4.0,211.0,31.0,6.0,7.0,20.0,10.0,14.0
6,July,20.0,9.0,5.0,7.0,18.0,22.0,20.0,36.0,16.0,23.0,13.0,9.0,28.0,13.0,8.0,22.0,29.0,49.0,40.0,28.0,8.0,5.0,5.0,23.0,44.0,7.0,8.0,19.0,10.0,13.0
7,August,9.0,5.0,4.0,5.0,9.0,13.0,19.0,21.0,7.0,10.0,8.0,4.0,14.0,6.0,4.0,13.0,13.0,31.0,20.0,14.0,4.0,4.0,4.0,11.0,27.0,4.0,4.0,8.0,4.0,8.0
8,September,18.0,4.0,4.0,4.0,8.0,16.0,15.0,21.0,4.0,10.0,7.0,5.0,16.0,6.0,4.0,16.0,14.0,29.0,19.0,9.0,7.0,4.0,4.0,10.0,24.0,4.0,4.0,9.0,4.0,8.0
9,October,43.0,30.0,6.0,28.0,23.0,71.0,67.0,85.0,27.0,41.0,27.0,20.0,48.0,25.0,19.0,96.0,80.0,84.0,95.0,42.0,23.0,12.0,9.0,67.0,95.0,30.0,29.0,40.0,17.0,26.0
10,November,41.0,22.0,5.0,25.0,19.0,76.0,72.0,56.0,24.0,32.0,30.0,20.0,33.0,18.0,14.0,59.0,68.0,96.0,86.0,43.0,20.0,11.0,11.0,56.0,69.0,21.0,24.0,38.0,24.0,22.0
11,December,29.0,22.0,4.0,21.0,26.0,65.0,57.0,104.0,26.0,29.0,26.0,19.0,39.0,22.0,15.0,68.0,61.0,76.0,74.0,43.0,26.0,10.0,8.0,72.0,94.0,12.0,27.0,33.0,21.0,31.0

below is the last file that i wrangled data for will be every teams popularity over just the year, no weeks, months will be included, just the totals for the year

In [26]:
yearlydata = pd.read_csv('nbateamsyearly.csv', sep = ',')

In [27]:
yearlydata

,Boston Celtics,Philadelphia 76ers,Toronto Raptors,Brooklyn Nets,New York Knicks,Milwaukee Bucks,Cleveland Cavaliers,Chicago Bulls,Indiana Pacers,Detroit Pistons,Atlanta Hawks,Washington Wizards,Miami Heat,Charlotte Hornets,Orlando Magic,Denver Nuggets,Minnesota Timberwolves,Utah Jazz,Portland Trail Blazers,Oklahoma City Thunder,Phoenix Suns,Los Angeles Clippers,Sacramento Kings,Golden State Warriors,Los Angeles Lakers,New Orleans Pelicans,Memphis Grizzlies,Dallas Mavericks,San Antonio Spurs,Houston Rockets
0,822,328,78,248,221,874,536,859,224,314,293,172,715,220,128,729,799,823,649,375,294,106,80,948,730,218,387,637,165,220

for my final analysis i will mainly be using the last 2 dataframes that i pulled in. my plan is to have charts by month for each team, and then a final one by year, and based on that, i will determine what teams are the most popular, as well as what time of year the nba is most popular as well awhy that may be